htseq/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

# admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/pending/(?P<id>\d+)/delete/$', 'htseq.centres.views.delete_pending_update', name='delete-pending'),
    url(r'^admin/pending/(?P<id>\d+)/approve/$', 'htseq.centres.views.approve_pending_update', name='approve-pending'),
    (r'^admin/pending/', 'htseq.centres.views.pending_updates'),
    (r'^admin/(.*)', admin.site.urls),
    url(r'^serial', 'htseq.serial.views.serial', name='serial'),
    url(r'^stats', 'htseq.stats.views.stats', name='stats'),
    url(r'^data.json', 'htseq.centres.views.json_list', name='json-data'),
    url(r'^capabilities.json', 'htseq.centres.views.capabilities_json', name='capabilities-json-data'),
    url(r'^platforms/(?P<p_slug>.*)/', 'htseq.centres.views.platform', name='platform'),
    url(r'^centres/(?P<c_slug>.*)/update/$', 'htseq.centres.views.centre_update', name='centre-update'),
    url(r'^centres/(?P<c_slug>.*)/$', 'htseq.centres.views.centre', name='centre'),
    url(r'^update/(?P<id>\d+)/$', 'htseq.centres.views.update_capabilities', name='update-capabilities'),
    url(r'^add/$', 'htseq.centres.views.add_centre', name='add-centre'),
    url(r'^',  'htseq.centres.views.index', name='main')
)

htseq/centres/models.py
from django.db import models
from django.contrib import admin
from django.template.defaultfilters import slugify
from django.db.models import AutoField
from django.core.exceptions import ObjectDoesNotExist

def get_fields(obj):
    fields = dict([(f.name, getattr(obj, f.name))
                   for f in obj._meta.fields
                   if not isinstance(f, AutoField) and\
                       not f in obj._meta.parents.values()])
    return fields

def copy_model_instance(obj, newobj):
    initial = get_fields(obj)
    return newobj(**initial)

class Location(models.Model):
    name = models.TextField(max_length=100)
    
    sw_lat = models.FloatField(null=True)
    sw_long = models.FloatField(null=True)
    ne_lat = models.FloatField(null=True)
    ne_long = models.FloatField(null=True)

    def __unicode__(self):
        return self.name

    class Meta:
        abstract = True

class Continent(Location):
    pass
        
class Country(Location):
    country_code = models.TextField(max_length=2)
    continent = models.ForeignKey(Continent, null=True)

class CentreBase(models.Model):
    name = models.CharField(max_length=100)
    slug = models.CharField(max_length=100, db_index=True, unique=True)
    url = models.URLField(max_length=255, help_text='The official website for this sequencing facility')
    notes = models.TextField(blank=True)
    lat = models.FloatField(help_text='Drag the map marker to change the position of this facility')
    long = models.FloatField()
    service_facility = models.NullBooleanField(help_text='Does this facility offer a sequencing service to the public?')
    dedicated_genome_centre = models.NullBooleanField(help_text='Is this facility a dedicated genome-sequencing centre?')
    contact_name = models.CharField(null=True, blank=True, max_length=100, help_text='The contact name for enquiries to this sequencing centre')
    contact_email = models.CharField(null=True, blank=True, max_length=100)
    contact_mask = models.CharField(null=True, blank=True, max_length=100)
    locality = models.CharField(max_length=100)
    country = models.ForeignKey(Country, null=True)
    capacity_summary = models.TextField(null=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    
    def __unicode__(self):
        return self.name

    @property
    def email_bits(self):
        return self.contact_email.split("@")

    @property
    def case_insensitive_name(self):
        return self.name.lower()

    @property
    def loc(self):
        return "%s, %s" % (self.locality, self.country)

    def save(self):
        self.slug = slugify(self.name)
        super(CentreBase, self).save()

    class Meta:
        abstract = True

class Centre(CentreBase):
    def save(self):
        self.capacity_summary = ''
        cs = ''
        for cc in self.centrecapacity_set.all():
            try:
               if cc.number_machines:
                  cs += " %d x " % (cc.number_machines)
               cs += cc.platform.short_name
               cs += ','
            except ObjectDoesNotExist, e: 
               print "Skipping as platform not exist"
        self.capacity_summary = cs.rstrip(',')
        super(Centre, self).save()

    def merge(self, obj):
        fields = get_fields(self)
        for f in fields.keys():
            setattr(self, f, getattr(obj, f))

    class Meta:
        db_table = 'centre'

class ComparisonLine:
    def __init__(self, field, x, y):
        self.old = x
        self.new = y
        if self.old == self.new:
            self.changed = False
        else:
            self.changed = True
        self.field = field

class PendingCentreUpdate(CentreBase):
    ip_address = models.CharField(max_length=16)
    email_address = models.CharField(max_length=200)
    update_to = models.ForeignKey(Centre, null=True)
    processed = models.BooleanField()

    @property
    def update_type(self):
        if self.update_to:
            return 'update'
        else:
            return 'new'

    @property
    def compare(self):
        c = self.update_to
        if not c:
            c = Centre()
        lines = []
        for f in get_fields(c):
            lines.append(ComparisonLine(f, getattr(c, f), getattr(self, f)))
        return lines
    
class Platform(models.Model):
    short_name = models.TextField()
    long_name = models.TextField()
    slug = models.TextField(db_index=True)    
    manufacturer_website = models.TextField()

    def __unicode__(self):
        return self.short_name
    
    class Meta:
        db_table = 'platform'
    
class CentreCapacityBase(models.Model):
    platform = models.ForeignKey(Platform)
    number_machines = models.IntegerField(null=True, blank=True)
    
    def __unicode__(self):
        return "%s - %s" % (str(self.centre), str(self.platform))
    
    class Meta:
        abstract = True
        
class CentreCapacity(CentreCapacityBase):
    centre = models.ForeignKey(Centre)

    class Meta:
        db_table = 'centre_capacity'

class PendingCentreCapacity(CentreCapacityBase):
    centre = models.ForeignKey(PendingCentreUpdate)

class CapacityInline(admin.TabularInline):
    model = CentreCapacity

class CentreAdmin(admin.ModelAdmin):
    inlines = [
        CapacityInline,
    ]

class PendingCapacityInline(admin.TabularInline):
    model = PendingCentreCapacity

class PendingCentreAdmin(admin.ModelAdmin):
    inlines = [
        PendingCapacityInline,
    ]

#admin.site.register(Centre, CentreAdmin)
# admin.site.register(Platform)
#admin.site.register(CentreCapacity)
#admin.site.register(Country)
#admin.site.register(Continent)
#admin.site.register(PendingCentreUpdate, PendingCentreAdmin)

htseq/centres/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render_to_response, get_object_or_404
from django.core import serializers
from django.forms.models import inlineformset_factory
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import user_passes_test
from django.template import RequestContext

from forms import CentreForm
from geolocate import geolocate
import json
from django.conf import settings
import pygeoip

from models import Centre, CentreCapacity, Platform, Country, copy_model_instance, PendingCentreUpdate, PendingCentreCapacity, get_fields

def hash_by_attribute(queryset, attribute):
    hash = {}
    for rec in queryset:
        val = getattr(rec, attribute)
        if val in hash:
            hash[val].append(rec)
        else:
            hash[val] = [rec]
    return hash, sorted(hash.keys())

def lookup_country(request):
    gi = pygeoip.GeoIP(settings.GEOIP_DATA)
    country_code = gi.country_code_by_addr(request.META.get('REMOTE_ADDR') )
    if not country_code:
        return 'GB'
    return country_code

def standard_items(request):
    centres = Centre.objects.select_related('country').order_by('country__name', 'name')
    return {'google_api_key' : settings.GOOGLE_API_KEY,
            'centres' : centres,
            'static_path' : settings.STATIC_PATH,
            'centre_mode' : False,
            'static_version' : settings.STATIC_VERSION,
            'platforms' : Platform.objects.order_by('short_name'),
            'country' : lookup_country(request)
    }

def index(request):
    params = standard_items(request)
    params['recent'] = Centre.objects.all().order_by('-id')[0:4]
    return render_to_response('index.html', params)

def make_capability_matrix(request):
    {'centres' : [platform]}

def country_to_dict(c):
    return {'name' : str(c.name), 'sw_lat' : str(c.sw_lat), 'sw_long' : str(c.sw_long), 'ne_lat' : str(c.ne_lat), 'ne_long' : str(c.ne_long)}

def objects_to_dict(objects, fields, attrs):
    r = []
    for o in objects:
        d = dict([(k, unicode(v)) for k, v in get_fields(o).iteritems() if k in fields])
        d.update(dict([(a, getattr(o, a)) for a in attrs]))
        r.append(d)
    return r

def get_centres_with_count(service_provider=False):
    from django.db import models
    centrecapacitylist = CentreCapacity.objects.select_related('centre', 'centre__country')
    if service_provider:
        centrecapacitylist = centrecapacitylist.filter(centre__service_facility=True)
    centres = {}
    for capacity in centrecapacitylist:
        if capacity.centre.pk in centres:
            centre = centres[capacity.centre.pk]
        else:
            centre = capacity.centre
            centres[centre.pk] = centre
        n = getattr(centre, 'n', 0)
        if capacity.number_machines:
            n += capacity.number_machines
        else:
            n += 1
        setattr(centre, 'n', n)
    centres = centres.values()
    import operator
    centres.sort(key=operator.attrgetter('case_insensitive_name'))
    return centres

from django.views.decorators.cache import cache_page
@cache_page(60 * 15)
def json_list(request):
    response = HttpResponse(content_type='application/json')

    json_object = {}
    # centres = Centre.objects.select_related('country')
    centres = get_centres_with_count()
    json_object['centres'] = objects_to_dict(centres, fields=('name', 'slug', 'lat', 'long', 'capacity_summary'), attrs=('n', 'loc',))

    # json_object['platform'] = objects_to_dict(Platform.objects.all(), fields=('short_name',))
    # json_object['capabilities'] = objects_to_dict(CentreCapacity.objects.all(), fields=('centre', 'platform'))

    countries = {}
    for centre in centres:
        countries[str(centre.country.name)] = country_to_dict(centre.country)
    json_object['countries'] = countries

    json.dump(json_object, response, ensure_ascii=False)
    return response

def capabilities_json(request):
    response = HttpResponse(content_type='application/json')
    id_list = request.GET['platform'].strip().split(',')
    id_list = [id for id in id_list if id != '']

    service_provider = False
    if 'service' in id_list:
        service_provider = True
        id_list.remove('service')

    mode = request.GET.get('mode', 'OR')
    if len(id_list):
        capabilities = CentreCapacity.objects.select_related('centre').filter(platform__in=id_list)
        if service_provider:
            capabilities = capabilities.filter(centre__service_facility=True)
        centre_counts = {}
        if mode == 'AND':
            centres = {}
            for c in capabilities:
                if c.centre.pk in centres:
                    centre = centres[c.centre.pk]
                else:
                    centre = c.centre
                    centres[centre.pk] = centre

                if c.centre in centre_counts:
                    centre_counts[c.centre] += 1
                else:
                    centre_counts[c.centre] = 1

                n = getattr(centre, 'n', 0)
                if c.number_machines:
                    n += c.number_machines
                else:
                    n += 1
                setattr(centre, 'n', n)

            centres = [centres[c.pk] for c, count in centre_counts.iteritems() if count == len(id_list)]
        elif mode == 'OR':
            centres = [c.centre for c in capabilities]
    else:
        centres = get_centres_with_count(service_provider)
    capabilities = objects_to_dict(centres, fields=('name', 'slug', 'lat', 'long', 'capacity_summary'), attrs=('n', 'loc',))
    json.dump(capabilities, response, ensure_ascii=False)
    return response

def centre(request, c_slug):
    params = standard_items(request)
    params['c'] = get_object_or_404(Centre, slug=c_slug)
    params['capacity'] = CentreCapacity.objects.filter(centre=params['c']).order_by('centre__name')
    params['centre_mode'] = True
    return render_to_response('centre.html', params)

def platform(request, p_slug):
    platform = Platform.objects.get(slug=p_slug)
    centres = CentreCapacity.objects.filter(platform=platform).select_related('centre').order_by('centre__name')
    centres = [c.centre for c in centres]
    return render_to_response('platform.html', {'p' : platform, 'centres' : centres})

def update_form(c):
    params = {}
    params['form'] = CentreForm(instance=c)
    #CapacityFormSet = inlineformset_factory(Centre, CentreCapacity)
    #params['formset'] = CapacityFormSet(instance=c)
    return params

def centre_update(request, c_slug):
    params = standard_items(request)
    c = get_object_or_404(Centre, slug=c_slug)
    pcu = copy_model_instance(c, PendingCentreUpdate)

    if request.POST:
        f = CentreForm(request.POST, instance=pcu)
        if f.is_valid():
            pcu = f.save(commit=False)
            pcu.update_to = c
            pcu.processed = False
            pcu.ip_address = request.META.get('REMOTE_ADDR', 'n/a')
            pcu.email_address = 'n.j.loman@bham.ac.uk'

            pcu.save()
            return HttpResponseRedirect(reverse('update-capabilities', args=[pcu.id]))
    else:
        f = CentreForm(instance=pcu)
    params['form'] = f
    return render_to_response('update.html', params, context_instance=RequestContext(request))

def add_centre(request):
    params = standard_items(request)

    if request.POST:
        f = CentreForm(request.POST)
        if f.is_valid():
            pcu = f.save(commit=False)
            pcu.processed = False
            pcu.ip_address = request.META.get('REMOTE_ADDR', 'n/a')
            pcu.email_address = 'n.j.loman@bham.ac.uk'
            pcu.save()

            return HttpResponseRedirect(reverse('update-capabilities', args=[pcu.id]))
    else:
        c = PendingCentreUpdate()
        c.lat = request.GET.get('lat')
        c.long = request.GET.get('long')
        try:
            country_name, country_code, c.locality = geolocate(c.lat, c.long)
            c.country = Country.objects.get(country_code = country_code)
        except ValueError:
            pass

        f = CentreForm(instance=c)
    params['form'] = f
    return render_to_response('update.html', params, context_instance=RequestContext(request))

def update_capabilities(request, id):
    pcu = get_object_or_404(PendingCentreUpdate, pk=id)
    params = standard_items(request)

    PendingCentreCapacity.objects.filter(centre = pcu).delete()
    if pcu.update_to:
        for cc in CentreCapacity.objects.filter(centre = pcu.update_to):
            PendingCentreCapacity(centre = pcu, platform=cc.platform, number_machines=cc.number_machines).save()

    CapacityFormSet = inlineformset_factory(PendingCentreUpdate, PendingCentreCapacity)
    if request.POST:
        formset = CapacityFormSet(request.POST, instance=pcu)
        if formset.is_valid():
            formset.save()
        else:
            print formset.errors

        from django.core.mail import mail_admins
        mail_admins('Sequencing map updated', 'Visit http://pathogenomics.bham.ac.uk/hts/admin/pending/', fail_silently=True)
        return HttpResponse('Thanks for your update. It will be reviewed by our moderators. Back to the <a href="' + reverse('main') + '">home</a> page.')
    else:
        formset = CapacityFormSet(instance=pcu)
    params['form'] = formset
    params['caps_mode'] = True
          
    return render_to_response('update.html', params, context_instance=RequestContext(request))

@user_passes_test(lambda u: u.is_staff, login_url='/hts/admin/')
def pending_updates(request):
    updates = PendingCentreUpdate.objects.filter(processed=False).order_by('date_created')
    return render_to_response('pending-updates.html', {'updates' : updates})

def do_approve(id):
    u = get_object_or_404(PendingCentreUpdate, pk=id)
    if u.update_to:
        c = u.update_to
    else:
        c = Centre()
    c.merge(u)
    c.save()

htseq/templates/centre.html
<html>
    <head>
        <title>
            Next Generation Genomics: World Map of High-throughput Sequencers
        </title>
        <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
        <link rel="stylesheet" type="text/css" href="{{static_path}}/css/all.css?{{ static_version }}">
        <script type="text/javascript" src="{{static_path}}/js/jquery.all.js?{{ static_version }}"></script>
        <script type="text/javascript"
            src="http://maps.google.com/maps?file=api&amp;v=2&amp;key={{ google_api_key }}&sensor=false"></script>
        <script type="text/javascript" src="{{static_path}}/js/markerclusterer_packed.js?{{ static_version }}"></script>

        <script type="text/javascript">
            function hello( name, loc ) {
                loc = "@" + loc;
                loc = name + loc;
                loc = "mailto:" + loc;
                window.location = loc;
            }
        </script>
    </head>
    <body onunload="GUnload()">
        <h1>Next Generation Genomics: World Map of High-throughput Sequencers</h1>
        [<a href="{% url 'main' %}">home</a>]
        <h2>{{ c.name }}, {{ c.country }}</h2>
                 <p>
                     Do you work at this centre? Why not <a href="{% url 'centre-update' c.slug %}">update this centre's details</a>
                 </p>
                 <p id="url">
                     Visit this centre's website: <a href="{{ c.url }}">{{ c.url }}</a>
                 </p>
                 <p id="notes">
                     {{ c.notes }}
                 </p>
                 {% if c.service_facility %}
                 <p>
                     This facility offers a sequencing service to the public.
                 </p>
                 {% endif %}

                 {% if c.dedicated_genome_centre %}
                 <p>
                     This facility is a dedicated genome centre.
                 </p>
                 {% endif %}

                 {% if c.contact_name %}
                 <h2>Contact Details</h2>

                 <p id="contact_name">
                     Contact <a href="javascript:hello('{{ c.email_bits.0 }}', '{{ c.email_bits.1 }}')">{{ c.contact_name }}</a> for further details.
                 </p>
                 {% endif %}
                 <h2>Capacity</h2>

                 <p>This facility has the following capacity:
                 <ul>
                 {% for cap in capacity %}
                     <li><a href="{% url 'platform' p_slug=cap.platform.slug %}">{{ cap.platform.long_name }}</a>
                     {% if cap.number_machines %}
                          ({{ cap.number_machines }} machine{{ cap.number_machines|pluralize}})
                     {% endif %}
                 {% endfor %}
                 </ul>
            </span> 
        </div>
        <hr>
        {% include "footer.html" %}
    </body>
</html>

htseq/templates/footer.html
<div id="footer">
<p>
    The High-Throughput Sequencing Map site was conceived by
    <a href="http://www.cancer.cam.ac.uk/directory/profile.php?jamesh008">James Hadfield</a>
    (Cancer Research UK, Cambridge) and built by
    <a href="http://pathogenomics.bham.ac.uk/blog">Nick Loman</a> (University of Birmingham).
    The database is as only as good as you, the users. If you discover inaccuracies or omissions,
    please take the time to update or <a href="{% url 'add-centre' %}">add details</a>. The maintainers of the site are not
    responsible for any errors you might find!
</p>
<p>
    This site was built with the Google Maps API, <a href="http://www.jquery.com">JQuery</a>, MarkerClusterer, <a href="http://www.googlemapsbook.com/2007/03/06/clickable-labeledmarker/">LabeledMarker</a>, <a href="http://www.djangoproject.com">Django</a> and <a href="http://www.sqlite.org">SQLite</a> - thanks!
</p>
</div>
<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try {
var pageTracker = _gat._getTracker("UA-11695233-1");
pageTracker._trackPageview();
} catch(err) {}</script>

htseq/templates/pending-updates.html
<html>
    <head>
        <title>Pending Updates</title>
        <style type="text/css">
            td {
                font-family: Courier;
            }
        </style>
    </head>
    <body>
    <ul>
    {% for u in updates %}
        <li>{{ u }} ({{ u.update_type }}) {{ u.ip_address }} {{ u.email_address }} {{ u.date_created }}
        <table>
                {% for ln in u.compare %}
                <tr>
                    <th>
                        {{ ln.field }}
                    </th>
                    <td>
                        {{ ln.old }}
                    </td>
                    <td>
                        {% if ln.changed %}<font color="red">{% endif %}
                        {{ ln.new }}<br/>
                        {% if ln.changed %}</font>{% endif %}
                    </td>
                </tr>
                {% endfor %}
                <tr>
                    <th>
                        machines
                    </th>
                    <td>
                        {% for cc in u.update_to.centrecapacity_set.all %}
                            {{ cc.platform }} -&gt; {{ cc.number_machines }}
                        {% endfor %}
                    </td>
                    <td>
                        {% for cc in u.pendingcentrecapacity_set.all %}
                            {{ cc.platform }} -&gt; {{ cc.number_machines }}
                        {% endfor %}
                    </td>
                </tr>
        </table>
        <input type="button" onclick="javascript:window.location.replace('{% url 'approve-pending' u.id %}')" value="Approve">
        <input type="button" onclick="javascript:window.location.replace('{% url 'delete-pending' u.id %}')" value="Delete">

    {% endfor %}
    </ul>
    </body>
</html>
    

htseq/templates/platform.html
<html>
	<head>
		<title>
			High-throughput sequencer world map - {{ p.name }}
		</title>
	</head>
	<body>
			<p>&gt;&gt; <a href="{% url 'main' %}">High-throughput sequencer world map</a></p>
			<h1>{{ p.long_name }}</h1>

			<p>Manufacturer website: <a href="{{ p.manufacturer_website }}">{{ p.manufacturer_website }}</a>

			<h2>Centres with {{ p.short_name }} capacity</h2>
			<ul>
				{% for c in centres %}
					<li><a href="{% url 'centre' c.slug %}">{{ c.name }}</a>
					{% if c.number_machines %}
						({{ c.number_machines }})
					{% endif %}
				{% endfor %}
			</ul>


	</body>
</html>

htseq/templates/update.html
<html>
    <head>
        <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
        <style type="text/css">
            h1 {
                font-family: Georgia, Garamond;
            }
            h2 {
                font-family: Georgia, Garamond;
            }
            td {
                font-family: Arial;
                margin-left: 20px;
            }
            th { 
                font-family: Arial;
                text-align: right;
                vertical-align: top;
            }
            input {
                width: 300px;
                font-family: Verdana;
                font-size: 16px;
            }
            textarea {
                width: 600px;
                height: 100px;
                font-family: Verdana;
            }
        </style>
        <script type="text/javascript" src="{{static_path}}/js/jquery-1.3.2.min.js"></script>

        <script src="http://maps.google.com/maps?file=api&v=2&key={{ google_api_key }}&sensor=false" type="text/javascript"></script> 
        <script type="text/javascript"> 
            function lat() {
                return $('#id_lat').val();
            }
            function set_lat(lat) {
                $('#id_lat').val(lat);
            }
            function lon() {
                return $('#id_long').val();
            }
            function set_lon(lon) {
                $('#id_long').val(lon);
            }

            function initialize() {
                    var map = new GMap2(document.getElementById("map_canvas"));
                    map.addControl(new GLargeMapControl());
                    map.addControl(new GMapTypeControl());

                    var center = new GLatLng(lat(), lon());
                    map.setCenter(center, 13);
 
                    var marker = new GMarker(center, {draggable: true});
 
                    GEvent.addListener(marker, "dragstart", function() {
                        map.closeInfoWindow();
                    });
 
                    GEvent.addListener(marker, "dragend", function() {
                        var latlng = marker.getLatLng();
                        set_lat(latlng.lat());
                        set_lon(latlng.lng());
                    });
                    map.addOverlay(marker);

                    /*
                    $('#id_lat').attr('disabled', 1);
                    $('#id_long').attr('disabled', 1);
                    */
            }
        </script> 
    <body onload="initialize()" onunload="GUnload()">
        <h1>Genomics: High-throughput Sequencing Facilities</h1> [<a href="{% url 'main' %}">home</a>]
        <h2>{{ c.name }}</h2>
        {% if caps_mode %}
        <h3>Update Capabilities</h3>
        <p>
           Please list high-throughput sequencing equipment currently in-place at this facility. If you
           do not know how many machines are there, leave that field blank but select the machine
           name.
        </p>
        {% else %}
        <h2>Update Centre Details</h3>
        {% endif %}
        <form method="POST" action="?">
            {% csrf_token %}
            {% if not caps_mode %}
            <div id="map_region" style="float: right;">
                <div id="map_canvas" style="width: 500px; height: 300px;"></div>
                <p>
                    <b>Please drag marker to location of facility.</b>
                </p>
            </div>
            {% endif %}
            <table>
                {{ form.as_table }}
                <tr>
                    <td></td><td><input type="submit" value=" Submit changes "></td>
                </tr>
            </table>
        </form>
        {% include "footer.html" %}
    </body>
</html>